/**
 * Swagger Configuration
 * ----------------------
 * This configuration file sets up Swagger for our API documentation.
 * It uses swagger-jsdoc to generate documentation based on JSDoc comments
 * in our route files and swagger-ui-express to serve the documentation.
 */

import swaggerJSDoc from "swagger-jsdoc";
import swaggerUi from "swagger-ui-express";
import dotenv from "dotenv";

// Load environment variables from .env file
dotenv.config();

// Determine the server URL dynamically based on environment variables.
// The SWAGGER_SERVER_URL can be optionally set in .env, or fallback to a default.
const serverUrl =
  process.env.SWAGGER_SERVER_URL ||
  `${process.env.SCHEME}://${process.env.HOST}:${process.env.PORT}/api`;

// Options for swagger-jsdoc
const options = {
  definition: {
    openapi: "3.0.0", // Specifies the OpenAPI version
    info: {
      title: "MERN Daily Task Tracker API", // Title of the API documentation
      version: "1.0.0", // API version
      description:
        "API documentation for the MERN Daily Task Tracker application. This documentation covers endpoints for authentication (local and social) and task management, with endpoints automatically generated by swagger-jsdoc.",
    },
    servers: [
      {
        url: serverUrl,
        description: "Server URL (configured via environment variables)",
      },
    ],
  },
  // The 'apis' field should list the files containing Swagger annotations.
  // Adjust these paths if your file structure changes.
  apis: ["./routes/*.js", "./controllers/*.js"],
};

// Generate the Swagger specification
const swaggerSpec = swaggerJSDoc(options);

/**
 * Setup Swagger
 * -------------
 * This function mounts the Swagger UI at the '/api-docs' endpoint.
 *
 * @param {object} app - The Express application object.
 */
export function setupSwagger(app) {
  // Serve Swagger UI using swagger-ui-express
  app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(swaggerSpec));

  // Optional: Log the generated Swagger spec for debugging purposes.
  // console.log(JSON.stringify(swaggerSpec, null, 2));
}
